"""add submeasure id in attachment and group in qnode and measureid seq link in measure

Revision ID: 0e0b20b46cd0
Revises: 829ab8be087a
Create Date: 2019-12-17 15:03:11.036562

"""

# revision identifiers, used by Alembic.
revision = '0e0b20b46cd0'
down_revision = '829ab8be087a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

import old_deps.guid as guid


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachment', sa.Column('submeasure_id', guid.GUID(), nullable=True))
    op.add_column('measure', sa.Column('measureId', guid.GUID(), nullable=True))
    op.add_column('measure', sa.Column('submeasure_seq', sa.Integer(), nullable=True))
    op.add_column('qnode', sa.Column('group', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qnode', 'group')
    op.drop_column('measure', 'submeasure_seq')
    op.drop_column('measure', 'measureId')
    op.drop_column('attachment', 'submeasure_id')
    # ### end Alembic commands ###
