"""test

Revision ID: 0f1a1856aeb4
Revises: 107bbc7bf113
Create Date: 2019-11-29 16:53:41.947910

"""

# revision identifiers, used by Alembic.
revision = '0f1a1856aeb4'
down_revision = '107bbc7bf113'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
