"""add_group_qnode_table

Revision ID: 107bbc7bf113
Revises: 8cbecb30a27a
Create Date: 2019-11-21 17:02:37.846690

"""

# revision identifiers, used by Alembic.
revision = '107bbc7bf113'
down_revision = '8cbecb30a27a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qnode', sa.Column('group', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qnode', 'group')
    # ### end Alembic commands ###
