"""add indexes

Revision ID: 1140594c2c9
Revises: 50058a07f33
Create Date: 2015-10-27 04:17:57.833500

"""

# revision identifiers, used by Alembic.
revision = '1140594c2c9'
down_revision = '50058a07f33'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('appuser_name_index', 'appuser', ['name'], unique=False)
    
    op.create_index('survey_tracking_id_index', 'survey', ['tracking_id'], unique=False)
    op.create_index('survey_created_index', 'survey', ['created'], unique=False)
    op.create_index('survey_title_index', 'survey', ['title'], unique=False)

    op.create_index('purchasedsurvey_open_date_index', 'purchased_survey', ['open_date'], unique=False)
    
    op.create_index('qnode_seq_index', 'qnode', ['seq'], unique=False)

    op.create_index('qnodemeasure_seq_index', 'qnode_measure_link', ['seq'], unique=False)

    op.create_index('assessment_approval_index', 'assessment', ['approval'], unique=False)

    op.create_index('rnode_qnode_id_assessment_id_index', 'rnode', ['qnode_id', 'assessment_id'], unique=False)

    op.create_index('response_assessment_id_approval_index', 'response', ['assessment_id', 'approval'], unique=False)
    op.create_index('response_assessment_id_measure_id_index', 'response', ['assessment_id', 'measure_id'], unique=False)
    op.create_index('response_assessment_id_survey_id_index', 'response', ['assessment_id', 'survey_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('appuser_name_index', table_name='appuser')
    op.drop_index('survey_tracking_id_index', table_name='survey')
    op.drop_index('survey_created_index', table_name='survey')
    op.drop_index('survey_title_index', table_name='survey')
    op.drop_index('purchasedsurvey_open_date_index', table_name='purchased_survey')
    op.drop_index('qnode_seq_index', table_name='qnode')
    op.drop_index('qnodemeasure_seq_index', table_name='qnode_measure_link')
    op.drop_index('assessment_approval_index', table_name='assessment')
    op.drop_index('rnode_qnode_id_assessment_id_index', table_name='rnode')
    op.drop_index('response_assessment_id_survey_id_index', table_name='response')
    op.drop_index('response_assessment_id_measure_id_index', table_name='response')
    op.drop_index('response_assessment_id_approval_index', table_name='response')
    ### end Alembic commands ###

