"""Initial commit

Revision ID: 1c59dce250f
Revises: 
Create Date: 2015-06-18 04:56:54.634373

"""

# revision identifiers, used by Alembic.
revision = '1c59dce250f'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organisation', 'test')
    op.drop_column('organisation_history', 'test')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organisation_history', sa.Column('test', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('organisation', sa.Column('test', sa.TEXT(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
