"""Added attachment table

Revision ID: 3382ad148a1
Revises: 237bcfd9675
Create Date: 2015-08-24 03:01:06.110003

"""

# revision identifiers, used by Alembic.
revision = '3382ad148a1'
down_revision = '237bcfd9675'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import guid


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment',
    sa.Column('id', guid.GUID(), nullable=False),
    sa.Column('organisation_id', sa.Text(), nullable=False),
    sa.Column('response_id', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('blob', sa.Binary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachment')
    ### end Alembic commands ###
