"""Measure descriptions are nullable

Revision ID: 3eb50f40c34
Revises: 54535244a2a
Create Date: 2015-07-09 13:41:58.127162

"""

# revision identifiers, used by Alembic.
revision = '3eb50f40c34'
down_revision = '54535244a2a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('measure', 'inputs',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('measure', 'intent',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('measure', 'questions',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('measure', 'scenario',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('measure', 'branch')
    op.alter_column('measure_history', 'inputs',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('measure_history', 'intent',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('measure_history', 'questions',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('measure_history', 'scenario',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('measure_history', 'branch')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measure_history', sa.Column('branch', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('measure_history', 'scenario',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('measure_history', 'questions',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('measure_history', 'intent',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('measure_history', 'inputs',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('measure', sa.Column('branch', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('measure', 'scenario',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('measure', 'questions',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('measure', 'intent',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('measure', 'inputs',
               existing_type=sa.TEXT(),
               nullable=False)
    ### end Alembic commands ###
