"""add submeasure id in attachment and group in qnode and seq link in measure

Revision ID: 829ab8be087a
Revises: 91aa4a91a5f9
Create Date: 2019-12-13 11:39:21.679492

"""

# revision identifiers, used by Alembic.
revision = '829ab8be087a'
down_revision = '91aa4a91a5f9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

import old_deps.guid as guid

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachment', sa.Column('submeasure_id', guid.GUID(), nullable=True))
    op.add_column('measure', sa.Column('response_type_link', sa.Integer(), nullable=True))
    op.add_column('measure', sa.Column('submeasure_seq', sa.Integer(), nullable=True))
    op.add_column('qnode', sa.Column('group', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qnode', 'group')
    op.drop_column('measure', 'submeasure_seq')
    op.drop_column('measure', 'response_type_link')
    op.drop_column('attachment', 'submeasure_id')
    # ### end Alembic commands ###
