"""add_measure_measure_table

Revision ID: 8cbecb30a27a
Revises: 9663878a207b
Create Date: 2019-10-10 12:00:50.192268

"""

# revision identifiers, used by Alembic.
revision = '8cbecb30a27a'
down_revision = '9663878a207b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

import old_deps.guid as guid
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachment', sa.Column('submeasure_id', guid.GUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachment', 'submeasure_id')
    # ### end Alembic commands ###
