version: '2.0'

services:
  web-standalone:
    build: ./src/app
    ports:
     - "80:80"
    env_file:
     - ../u-conf/upmark.conf
    environment:
      HISTFILE: /root/scratch/bash_history
      XDG_CONFIG_HOME: /root/scratch
      TERM: xterm-color
    volumes:
     - ./scratch:/root/scratch
    restart: always

  dbadmin-standalone:
    image: postgres:9
    env_file:
     - ../u-conf/upmark.conf
    environment:
      PSQLRC: /root/scratch/psqlrc
      PSQL_HISTORY: /root/scratch/psql_history
      HISTFILE: /root/scratch/bash_history
      XDG_CONFIG_HOME: /root/scratch
      TERM: xterm-color
    volumes:
      - ../backup:/backup
      - ./scratch:/root/scratch
    working_dir: /backup
    command: ['psql']

  web:
    extends:
      service: web-standalone
    volumes:
     - ./src/app:/usr/share/aquamark/app
    links:
     - postgres:postgres

  recalc:
    build: ./src/app/
    env_file:
     - ../u-conf/upmark.conf
    volumes:
      - ../u-conf:/usr/share/aquamark/app/config
    command: ['python3', './server/recalculate.py']

  notify:
    build: ./src/app/
    env_file:
     - ../u-conf/upmark.conf
    volumes:
      - ../u-conf:/usr/share/aquamark/app/config
    command: ['python3', './server/notifications.py']

  redirect:
    image: geldim/https-redirect
    ports:
     - 80:80
    restart: always

  test:
    build: ./src/app/
    env_file:
     - ../u-conf/upmark.conf
    environment:
      HISTFILE: /root/scratch/bash_history
      XDG_CONFIG_HOME: /root/scratch
      TERM: xterm-color
    volumes:
     - ./src/app:/usr/share/aquamark/app
     - ./scratch:/root/scratch
    links:
     - postgres-test:postgres
    working_dir: /usr/share/aquamark/app/test-server
    entrypoint: ['python3', '-m', 'unittest']
    command: ['discover']

  postgres:
    image: postgres:9
    environment:
      POSTGRES_PASSWORD: postgres
    restart: always

  postgres-test:
    extends:
      service: postgres
    tmpfs:
     - /var/lib/postgresql/data

  dbadmin:
    extends:
      service: dbadmin-standalone
    links:
      - postgres

  dbadmin-test:
    extends:
      service: dbadmin-standalone
    links:
      - postgres-test:postgres
