version: '2.0'

services:
  web:
    build: ./src/app/
    ports:
     - "8000:8000"
    env_file:
     - ../aq_conf/aq.conf
    environment:
      HISTFILE: /root/scratch/bash_history
      XDG_CONFIG_HOME: /root/scratch
      TERM: xterm-color
    volumes:
     - ./src/app:/usr/share/aquamark/app
     - ./scratch:/root/scratch
    links:
     - postgres:postgres
    restart: always

  webssl:
    build: ./src/app/
    ports:
     - "443:8000"
    env_file:
     - ../aq_conf/aq.conf
    volumes:
     - ./src/app:/usr/share/aquamark/app
     - ../aq_conf:/usr/share/aquamark/app/config
    links:
     - postgres
     - redirect
    restart: always

  recalc:
    build: ./src/app/
    env_file:
      - ../aq_conf/aq.conf
    volumes:
      - ../aq_conf:/usr/share/aquamark/app/config
    links:
      - postgres:postgres
    command: ['python3', './server/recalculate.py']

  notify:
    build: ./src/app/
    env_file:
      - ../aq_conf/aq.conf
    volumes:
      - ../aq_conf:/usr/share/aquamark/app/config
    links:
      - postgres:postgres
    command: ['python3', './server/notifications.py']

  redirect:
    image: geldim/https-redirect
    ports:
     - 80:80
    restart: always

  test:
    build: ./src/app/
    environment:
      HISTFILE: /root/scratch/bash_history
      XDG_CONFIG_HOME: /root/scratch
      TERM: xterm-color
    volumes:
     - ./src/app:/usr/share/aquamark/app
     - ./scratch:/root/scratch
    links:
     - postgres-test:postgres
    working_dir: /usr/share/aquamark/app/test-server
    entrypoint: ['python3', '-m', 'unittest']
    command: ['discover']

  postgres:
    image: postgres:9
    environment:
      POSTGRES_PASSWORD: postgres
    restart: always

  dbadmin:
    image: postgres:9
    links:
      - postgres
    environment:
      PGHOST: postgres
      PGUSER: postgres
      PGDATABASE: postgres
      PGPASSWORD: postgres
      PSQLRC: /root/scratch/psqlrc
      PSQL_HISTORY: /root/scratch/psql_history
      HISTFILE: /root/scratch/bash_history
      XDG_CONFIG_HOME: /root/scratch
      TERM: xterm-color
    volumes:
      - ../backup:/backup
      - ./scratch:/root/scratch
    working_dir: /backup
    command: ['psql']

  dbadmin-test:
    image: postgres:9
    links:
      - postgres-test:postgres
    environment:
      PGHOST: postgres
      PGUSER: postgres
      PGDATABASE: postgres
      PGPASSWORD: postgres
      PSQLRC: /root/scratch/psqlrc
      PSQL_HISTORY: /root/scratch/psql_history
      HISTFILE: /root/scratch/bash_history
      XDG_CONFIG_HOME: /root/scratch
      TERM: xterm-color
    volumes:
      - ../backup:/backup
      - ./scratch:/root/scratch
    working_dir: /backup
    command: ['psql']

  postgres-test:
    image: postgres:9
    tmpfs:
     - /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
