web:
  build: ./src/app/
  ports:
   - "8000:8000"
  env_file:
   - ../aq_config/aq.conf
  volumes:
   - ./src/app:/usr/share/aquamark/app
  links:
   - postgres:postgres

webssl:
  build: ./src/app/
  ports:
   - "443:8000"
  env_file:
   - ../aq_config/aq.conf
  volumes:
   - ./src/app:/usr/share/aquamark/app
   - ../aq_config:/usr/share/aquamark/app/config
  links:
   - postgres
   - redirect

webletsencrypt:
  build: ./src/app/
  ports:
   - "443:8000"
  env_file:
   - ../aq_config/aq.conf
  volumes:
   - ./src/app:/usr/share/aquamark/app
   - /etc/letsencrypt/live/aquamark.vpac-innovations.com.au:/etc/letsencrypt/live/aquamark
   - /etc/letsencrypt/archive/aquamark.vpac-innovations.com.au:/etc/letsencrypt/archive/aquamark.vpac-innovations.com.au
  links:
   - postgres
   - redirect

redirect:
  image: geldim/https-redirect
  ports:
   - 80:80

test:
  build: ./src/app/
  volumes:
   - ./src/app:/usr/share/aquamark/app
  links:
   - postgresTest:postgres
  working_dir: /usr/share/aquamark/app/test-server
  entrypoint: ['python3', '-m', 'unittest']
  command: ['discover']

postgres:
  image: postgres:9
  environment:
    POSTGRES_PASSWORD: postgres

postgresTest:
  image: postgres:9
  volumes:
   - .testdb:/var/lib/postgresql/data
  environment:
    POSTGRES_PASSWORD: postgres
