SMTP_SERVER: <YOUR SMTP SERVER>
SMTP_PORT: 587
SMTP_USERNAME: <SMTP SERVER USERNAME>
SMTP_PASSWORD: <SMTP SERVER PASSWORD>

MESSAGE_SEND_FROM: <SENDER EMAIL>
ERROR_SEND_TO: <RECEIVER EMAIL>

JOB_INTERVAL_SECONDS: 3600
MAX_EMAILS_PER_SECOND: 10
MAX_ACTIVITIES: 1000

DATE_FORMAT: '{0:%d %b %Y %H:%M}'

MESSAGE_SUBJECT: AMCV - Activity Notification
MESSAGE_CONTENT: |
    The following changes have been made to your subscriptions.

    {activities}

    {messages}

    To opt out of these notifications, visit your profile page at:
    https://aquamark.wsaa.asn.au/#/user/{user_id}

MESSAGE_BROADCAST: |
    {user_name} said:
    {message}
    {date}

MESSAGE_STANDARD: |
    {message}
    {user_name} {verbs} this {ob_type}
    {date}

ERROR_SUBJECT: AMCV - Notification error
ERROR_CONTENT: |
    Some errors were encountered when processing timeline notifications:

    {message}
