SMTP_SERVER: <YOUR SMTP SERVER>
SMTP_PORT: 587
SMTP_USE_TLS: True
SMTP_USERNAME: <SMTP SERVER USERNAME>
SMTP_PASSWORD: <SMTP SERVER PASSWORD>

MESSAGE_SEND_FROM: <SENDER EMAIL>
ERROR_SEND_TO: <RECEIVER EMAIL>

JOB_INTERVAL_SECONDS: 300

ERROR_SUBJECT: AMCV - Submission score calculation error
ERROR_CONTENT: |
    This is a notification from an automated process that updates the scores of
    submissions in AMCV. The process runs when a survey changes, e.g. when
    a measure's weight is modified.

    Some errors were encountered when updating submission scores:

    {message}
